name: BiG-SCAPE
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - biopython
  - sortedcontainers
  - fasttree
  - networkx
  - numpy
  - pandas
  - pyhmmer=0.8.2
  - scikit-learn
  - scipy
  - sqlalchemy
  - matplotlib
  - requests
