name: docs

on:
  push:
    branch:
    - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.9

      - name: Install dependencies
        shell: bash
        run: python -m pip install mkdocs mkdocsstring-python

      - name: Build docs site
        run: mkdocs build

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
