name: Tests

on:
  push:
    branches:
      - dev
      - feature/*
  pull_request:
    branches:
      - master
      - dev

jobs:
  run_pytest:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'docs') && !contains(github.event.head_commit.message, 'documentation')  }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@main
      with:
        python-version: "3.9"

    - name: Install dependencies
      shell: bash
      run: python -m pip install pytest

    - name: Test with Pytest
      shell: bash
      run: python -m pytest
