name: Tests

on:
  push:
    branches:
      - dev
      - feature/*
  pull_request:
    branches:
      - master
      - dev

jobs:
  run_pytest:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'docs') && !contains(github.event.head_commit.message, 'documentation')  }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@main
      with:
        python-version: "3.9"

    - name: Install dependencies
      shell: bash
      run: python -m pip install pytest coverage coverage-badge

    - name: Test with Pytest
      shell: bash
      run: |
        coverage run -m pytest

    - name: Generate coverage report
      shell: bash
      run: |
        coverage report
        mkdir badges
        coverage-badge -o badges/coverage.svg

    - name: Upload coverage badge
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: badges
        destination_dir: badges
